name = "FixedSizeArrays"
uuid = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
version = "0.1.0"
authors = ["Mos√® Giordano <mose@gnu.org>"]

[weakdeps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extensions]
RandomExt = "Random"

[compat]
Random = "1"
julia = "1.10"
