name = "FixedSizeArrays"
uuid = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
version = "1.4.0"
authors = ["Mos√® Giordano <mose@gnu.org>, Neven Sajko <s@purelymail.com>, Oscar Smith <oscar.smith@juliacomputing.com>, and contributors"]

[deps]
CheckedSizeProduct = "1b2cc9da-92e3-4b71-9788-30fc110eefda"
Collects = "08986516-18db-4a8b-8eaa-f5ef1828d8f1"
LightBoundsErrors = "e21c612c-4641-4669-b9c3-3f4360ced9da"

[weakdeps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"

[extensions]
FixedSizeArraysRandomExt = "Random"
FixedSizeArraysAdaptExt = "Adapt"

[compat]
Adapt = "4"
CheckedSizeProduct = "1"
Collects = "1"
LightBoundsErrors = "1"
Random = "1"
julia = "1.10"
